### ISSUE TITLE
ValueError: Path cannot be empty 

### ISSUE THREAD

**Issue by lispstudent** [cosmocode/dokuwiki-plugin-photogallery#4]
Hello,

While testing PhotoGallery Plugin with this code:

```
---- photogallery show ----
namespace  : .:g
title      : Test gallery
----
```

The `g` namespace [get displayed, but it is not clickable](https://www.gandharvalokapublishers.in/index)

Alos, this shows up in the logs:

```
2023-01-11 16:41:23ValueError: Path cannot be empty /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/fetch.functions.php(89)
    #0 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/fetch.functions.php(89): fopen()
    #1 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/plugins/photogallery/pgFetch.php(100): sendFile()
    #2 {main} 
```

**Comment by annda** [comment]
Please deactivate the Feature Flag [defer_js](https://www.dokuwiki.org/config:defer_js) in your configuration for now. We are working on updating the JavaScript library in this plugin.

I have updated the official documentation accordingly.

**Comment by lispstudent** [comment]
Thank you very much, this fixes the problem.

Thank you, much appreciated.
