### ISSUE TITLE
Sort by file dosn't work

### ISSUE THREAD

**Issue by Albewue** [cosmocode/dokuwiki-plugin-photogallery#5]
I'm using this plugin on an xampp Apache with PHP 7.4.15. First it seems that everything is fine but then i mentioned that the sort order of the shown pictures is not right. I think there is a bug in the sorting routine - please check it.

**Comment by annda** [comment]
Can you tell us more about your environment?

- DokuWiki Version
- Locale: append `&do=check` to URL

**Comment by Albewue** [comment]
The update of 2023-01-30 fixed this problem - thank's
